services:
  - type: web
<<<<<<< HEAD
    name: chibatoru-online
=======
    name: chibatoru-ws
>>>>>>> 87698a44a2b93256cbe1746d91c2747e436ba30b
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
